/* All addressing modes supported by the 6502 CPU */
#[derive(Debug, Clone, Copy)]
pub enum AddressingMode {
    Accumulator,
    Implied,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
}

/* All instructions supported by the 6502 CPU */
#[derive(Debug)]
pub enum Instruction {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

/*
 * An Opcode represents a CPU instruction along with its
 * addressing mode. Additional information such as the
 * instruction's byte length and the number of cycles
 * required to execute it is also included here
 */
#[derive(Debug)]
pub struct Opcode {
    pub instruction: Instruction,
    pub addressing_mode: AddressingMode,
    pub bytes: u8,
    pub cycles: u8,
}

impl Opcode {
    /* Decodes a specific byte and translates it into a meaningful Opcode */
    pub fn decode(byte: u8) -> Option<Self> {
        match byte {
            0x00 => Some(Opcode {
                instruction: Instruction::BRK,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 7,
            }),
            0x01 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x05 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x06 => Some(Opcode {
                instruction: Instruction::ASL,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x08 => Some(Opcode {
                instruction: Instruction::PHP,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 3,
            }),
            0x09 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x0A => Some(Opcode {
                instruction: Instruction::ASL,
                addressing_mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x0D => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x0E => Some(Opcode {
                instruction: Instruction::ASL,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x10 => Some(Opcode {
                instruction: Instruction::BPL,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x11 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0x15 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x16 => Some(Opcode {
                instruction: Instruction::ASL,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x18 => Some(Opcode {
                instruction: Instruction::CLC,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x19 => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x1D => Some(Opcode {
                instruction: Instruction::ORA,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x1E => Some(Opcode {
                instruction: Instruction::ASL,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0x20 => Some(Opcode {
                instruction: Instruction::JSR,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x21 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x24 => Some(Opcode {
                instruction: Instruction::BIT,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x25 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x26 => Some(Opcode {
                instruction: Instruction::ROL,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x28 => Some(Opcode {
                instruction: Instruction::PLP,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 4,
            }),
            0x29 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x2A => Some(Opcode {
                instruction: Instruction::ROL,
                addressing_mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x2C => Some(Opcode {
                instruction: Instruction::BIT,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x2D => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x2E => Some(Opcode {
                instruction: Instruction::ROL,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x30 => Some(Opcode {
                instruction: Instruction::BMI,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x31 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0x35 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x36 => Some(Opcode {
                instruction: Instruction::ROL,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x38 => Some(Opcode {
                instruction: Instruction::SEC,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x39 => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x3D => Some(Opcode {
                instruction: Instruction::AND,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x3E => Some(Opcode {
                instruction: Instruction::ROL,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0x40 => Some(Opcode {
                instruction: Instruction::RTI,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 6,
            }),
            0x41 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x45 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x46 => Some(Opcode {
                instruction: Instruction::LSR,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x48 => Some(Opcode {
                instruction: Instruction::PHA,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 3,
            }),
            0x49 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x4A => Some(Opcode {
                instruction: Instruction::LSR,
                addressing_mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x4C => Some(Opcode {
                instruction: Instruction::JMP,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 3,
            }),
            0x4D => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x4E => Some(Opcode {
                instruction: Instruction::LSR,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x50 => Some(Opcode {
                instruction: Instruction::BVC,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x51 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0x55 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x56 => Some(Opcode {
                instruction: Instruction::LSR,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x58 => Some(Opcode {
                instruction: Instruction::CLI,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x59 => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x5D => Some(Opcode {
                instruction: Instruction::EOR,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x5E => Some(Opcode {
                instruction: Instruction::LSR,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0x60 => Some(Opcode {
                instruction: Instruction::RTS,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 6,
            }),
            0x61 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x65 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x66 => Some(Opcode {
                instruction: Instruction::ROR,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x68 => Some(Opcode {
                instruction: Instruction::PLA,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 4,
            }),
            0x69 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x6A => Some(Opcode {
                instruction: Instruction::ROR,
                addressing_mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x6C => Some(Opcode {
                instruction: Instruction::JMP,
                addressing_mode: AddressingMode::Indirect,
                bytes: 3,
                cycles: 5,
            }),
            0x6D => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x6E => Some(Opcode {
                instruction: Instruction::ROR,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x70 => Some(Opcode {
                instruction: Instruction::BVS,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x71 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0x75 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x76 => Some(Opcode {
                instruction: Instruction::ROR,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x78 => Some(Opcode {
                instruction: Instruction::SEI,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x79 => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x7D => Some(Opcode {
                instruction: Instruction::ADC,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x7E => Some(Opcode {
                instruction: Instruction::ROR,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0x81 => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x84 => Some(Opcode {
                instruction: Instruction::STY,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x85 => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x86 => Some(Opcode {
                instruction: Instruction::STX,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x88 => Some(Opcode {
                instruction: Instruction::DEY,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x8A => Some(Opcode {
                instruction: Instruction::TXA,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x8C => Some(Opcode {
                instruction: Instruction::STY,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x8D => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x8E => Some(Opcode {
                instruction: Instruction::STX,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x90 => Some(Opcode {
                instruction: Instruction::BCC,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x91 => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 6,
            }),
            0x94 => Some(Opcode {
                instruction: Instruction::STY,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x95 => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x96 => Some(Opcode {
                instruction: Instruction::STX,
                addressing_mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0x98 => Some(Opcode {
                instruction: Instruction::TYA,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x99 => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 5,
            }),
            0x9A => Some(Opcode {
                instruction: Instruction::TXS,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x9D => Some(Opcode {
                instruction: Instruction::STA,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 5,
            }),
            0xA0 => Some(Opcode {
                instruction: Instruction::LDY,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xA1 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xA2 => Some(Opcode {
                instruction: Instruction::LDX,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xA4 => Some(Opcode {
                instruction: Instruction::LDY,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xA5 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xA6 => Some(Opcode {
                instruction: Instruction::LDX,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xA8 => Some(Opcode {
                instruction: Instruction::TAY,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xA9 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xAA => Some(Opcode {
                instruction: Instruction::TAX,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xAC => Some(Opcode {
                instruction: Instruction::LDY,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xAD => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xAE => Some(Opcode {
                instruction: Instruction::LDX,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xB0 => Some(Opcode {
                instruction: Instruction::BCS,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xB1 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0xB4 => Some(Opcode {
                instruction: Instruction::LDY,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xB5 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xB6 => Some(Opcode {
                instruction: Instruction::LDX,
                addressing_mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0xB8 => Some(Opcode {
                instruction: Instruction::CLV,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xB9 => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xBA => Some(Opcode {
                instruction: Instruction::TSX,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xBC => Some(Opcode {
                instruction: Instruction::LDY,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xBD => Some(Opcode {
                instruction: Instruction::LDA,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xBE => Some(Opcode {
                instruction: Instruction::LDX,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xC0 => Some(Opcode {
                instruction: Instruction::CPY,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xC1 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xC4 => Some(Opcode {
                instruction: Instruction::CPY,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xC5 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xC6 => Some(Opcode {
                instruction: Instruction::DEC,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0xC8 => Some(Opcode {
                instruction: Instruction::INY,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xC9 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xCA => Some(Opcode {
                instruction: Instruction::DEX,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xCC => Some(Opcode {
                instruction: Instruction::CPY,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xCD => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xCE => Some(Opcode {
                instruction: Instruction::DEC,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0xD0 => Some(Opcode {
                instruction: Instruction::BNE,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xD1 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0xD5 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xD6 => Some(Opcode {
                instruction: Instruction::DEC,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0xD8 => Some(Opcode {
                instruction: Instruction::CLD,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xD9 => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xDD => Some(Opcode {
                instruction: Instruction::CMP,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xDE => Some(Opcode {
                instruction: Instruction::DEC,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0xE0 => Some(Opcode {
                instruction: Instruction::CPX,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xE1 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xE4 => Some(Opcode {
                instruction: Instruction::CPX,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xE5 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xE6 => Some(Opcode {
                instruction: Instruction::INC,
                addressing_mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0xE8 => Some(Opcode {
                instruction: Instruction::INX,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xE9 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xEA => Some(Opcode {
                instruction: Instruction::NOP,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xEC => Some(Opcode {
                instruction: Instruction::CPX,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xED => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xEE => Some(Opcode {
                instruction: Instruction::INC,
                addressing_mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0xF0 => Some(Opcode {
                instruction: Instruction::BEQ,
                addressing_mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xF1 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),
            0xF5 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xF6 => Some(Opcode {
                instruction: Instruction::INC,
                addressing_mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0xF8 => Some(Opcode {
                instruction: Instruction::SED,
                addressing_mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xF9 => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xFD => Some(Opcode {
                instruction: Instruction::SBC,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xFE => Some(Opcode {
                instruction: Instruction::INC,
                addressing_mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            _ => None,
        }
    }
}
